/**
 * DataHarbor.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryLayoutMapping } from './categoryLayoutMapping';
import { FilesConfigurations } from './filesConfigurations';

export interface ProcessingConfiguration { 
    id?: string;
    name?: string;
    description?: string;
    modifiedOn?: Date;
    operatorFilesConfigurations?: FilesConfigurations;
    layoutMappings?: Array<CategoryLayoutMapping>;
}