﻿apiVersion: v1
kind: Service
metadata:
  name: dataharbor-client
spec:
  selector:
    app: dataharbor-client
  ports:
    - port: 8000
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataharbor-client
spec:
  selector:
    matchLabels:
      app: dataharbor-client
  template:
     metadata:
       labels:
         app: dataharbor-client
     spec:
       containers:
         - name: dataharbor-client
           image: pank05081985/dataharbor-client
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dataharbor-client
spec:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dataharbor-client
