apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dataharbor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: dataharbor.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: dataharbor-api
                port:
                  number: 7000
          - path: /(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: dataharbor-client
                port:
                  number: 8000
          - path: /prometheus(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
          - path: /grafana(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
          - path: /db(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ravendb
                port:
                  number: 9001