# ravendb-pvc.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ravendb-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ravendb  # This is on Minikube VM's disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ravendb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ravendb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ravendb
  template:
    metadata:
      labels:
        app: ravendb
    spec:
      containers:
      - name: ravendb
        image: ravendb/ravendb:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: ravendb-storage
          mountPath: /opt/RavenDB/Server/RavenData
        env:
        - name: RAVEN_Setup_Mode
          value: "None"  # Use "None" for unsecured single-node dev mode
      volumes:
      - name: ravendb-storage
        persistentVolumeClaim:
          claimName: ravendb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ravendb
spec:
  selector:
    app: ravendb
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP  # use LoadBalancer or NodePort for external access
