apiVersion: v1
kind: Service
metadata:
  name: ravendb
  labels:
    app: ravendb
spec:
  type: NodePort
  selector:
    app: ravendb
  ports:
    - name: http
      port: 9001
      targetPort: 9001
      nodePort: 30901
    - name: tcp
      port: 38888
      targetPort: 38888
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ravendb
spec:
  selector:
    matchLabels:
      app: ravendb
  serviceName: "ravendb"
  replicas: 1
  template:
    metadata:
      labels:
        app: ravendb
    spec:
      containers:
        - name: ravendb
          image: ravendb/ravendb:latest
          command: ["/bin/bash", "-c"]
          args: ["./run.sh --ServerUrl=http://0.0.0.0:9001"]
          ports:
            - containerPort: 9001
              name: http
            - containerPort: 38888
              name: tcp
          volumeMounts:
            - name: ravendb-storage
              mountPath: /opt/RavenDB/Server/RavenData
          env:
            - name: RAVEN_Security_UnsecuredAccessAllowed
              value: "PublicNetwork"
            - name: RAVEN_License_Eula_Accepted
              value: "true"
  volumeClaimTemplates:
    - metadata:
        name: ravendb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
        storageClassName: standard
