/**
 * DataHarbor.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProcessStatus } from './processStatus';
import { ProcessingLogEntry } from './processingLogEntry';

export interface Declaration { 
    uniqueId?: string;
    name?: string;
    description?: string;
    status?: ProcessStatus;
    recieveDate?: Date;
    files?: Array<Blob>;
    rawData?: Array<{ [key: string]: string; }>;
    transactions?: Array<{ [key: string]: string; }>;
    processingLogs?: Array<ProcessingLogEntry>;
}