/**
 * DataHarbor.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LayoutMapping { 
    id?: string;
    fieldName?: string;
    sourceColumn?: string;
    showInOutput?: boolean;
    fieldOrder?: number;
    fieldType?: string;
    formatPattern?: string;
    isUnique?: boolean;
    length?: number;
}