/**
 * DataHarbor.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ProcessingSeverity = 0 | 1 | 2 | 3 | 4 | 5;

export const ProcessingSeverity = {
    NUMBER_0: 0 as ProcessingSeverity,
    NUMBER_1: 1 as ProcessingSeverity,
    NUMBER_2: 2 as ProcessingSeverity,
    NUMBER_3: 3 as ProcessingSeverity,
    NUMBER_4: 4 as ProcessingSeverity,
    NUMBER_5: 5 as ProcessingSeverity
};