/**
 * DataHarbor.WebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type ProcessStatus = 'Anchored' | 'Docked' | 'Adrifted' | 'Dispatched' | 'Error';

export const ProcessStatus = {
    Anchored: 'Anchored' as ProcessStatus,
    Docked: 'Docked' as ProcessStatus,
    Adrifted: 'Adrifted' as ProcessStatus,
    Dispatched: 'Dispatched' as ProcessStatus,
    Error: 'Error' as ProcessStatus
};